---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: metadata-service
          image: metadata-service:7.0
          ports:
          - containerPort: 8080
          env:
          - name: APP_NAME
            valueFrom: 
              configMapKeyRef: 
                name: special-config
                key: name


---
apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    component: db
spec:
  containers:
  - name: mongo
    image: mongo
    ports:
      - containerPort: 27017
    volumeMounts:
    - mountPath: /data/db/
      name: mongo-volume
  volumes:
  - name: mongo-volume
    hostPath:
      path: /data
      type: Directory

--- 

kind: Service
apiVersion: v1
metadata:
 name: db-service
spec:
 selector:
   component: db
 ports:
 - protocol: TCP
   port: 27017
   targetPort: 27017
 type: NodePort